spring:
  threads:
    virtual:
      enabled: true
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/applicationdb

server:
  port: 8084

jwt:
  secret: mySuperqfqfqfqfqfqSecretKey1afaff23456dfffafqfqffqfqf
  expiration: 3600000 # 1 hour in ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}] %m%n"