spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: resume-parser-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.Abhijith.resume_parser_service.kafka.event.ResumeParseEvent
        spring.json.trusted.packages: "com.Abhijith.resume_parser_service.kafka.event"
  application:
    name: resume-parser-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/applicationdb


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

kafka:
  topics:
    resume-parse: resume-parse-topic

management:
  endpoints:
    web:
      exposure:
        include: "*"

