
services:

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"     # for clients
      - "9093:9093"     # for controller quorum
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=14bfe6cb-e7e3-4bce-a5b4-1d5ee555c2a2
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka

  redpanda-console:
    image: redpandadata/console:v2.3.6
    ports:
      - "8085:8080"
    environment:
      - KAFKA_BROKERS=localhost:9092
    depends_on:
      - kafka

volumes:
  kafka-data:
