server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: job-posting-service
              uri: lb://job-posting-service
              predicates:
                - Path=/jobs
                - Path=/jobs/**
              filters:
                - RewritePath=/jobs(?<segment>/?.*), /api/jobs${segment}

            - id: application-submit-service
              uri: lb://application-submit-service
              predicates:
                - Path=/applications
                - Path=/applications/**
              filters:
                - RewritePath=/applications(?<segment>/?.*), /api/applications${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
