server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: job-posting-service-root
              uri: lb://job-posting-service
              predicates:
                - Path=/jobs
              filters:
                - RewritePath=/jobs, /api/jobs

            - id: job-posting-service
              uri: lb://job-posting-service
              predicates:
                - Path=/jobs/**
              filters:
                - RewritePath=/jobs/(?<segment>.*), /api/jobs/${segment}

            - id: application-submit-service-root
              uri: lb://application-submit-service
              predicates:
                - Path=/applications
              filters:
                - RewritePath=/applications, /api/applications

            - id: application-submit-service
              uri: lb://application-submit-service
              predicates:
                - Path=/applications/**
              filters:
                - RewritePath=/applications/(?<segment>.*), /api/applications/${segment}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
