server:
  port: 8080

spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      enabled: true
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: job-posting-service-root
              uri: lb://job-posting-service
              predicates:
                - Path=/jobs
              filters:
                - RewritePath=/jobs, /api/jobs

            - id: job-posting-service
              uri: lb://job-posting-service
              predicates:
                - Path=/jobs/**
              filters:
                - RewritePath=/jobs/(?<segment>.*), /api/jobs/${segment}

            - id: application-submit-service-root
              uri: lb://application-submit-service
              predicates:
                - Path=/applications
              filters:
                - RewritePath=/applications, /api/applications

            - id: application-submit-service
              uri: lb://application-submit-service
              predicates:
                - Path=/applications/**
              filters:
                - RewritePath=/applications/(?<segment>.*), /api/applications/${segment}

            - id: auth-service-root
              uri: lb://auth-service
              predicates:
                - Path=/auth
              filters:
                - RewritePath=/auth, /api/auth

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /api/auth/${segment}

            - id: admin-service-root
              uri: lb://auth-service
              predicates:
                - Path=/admin/users
              filters:
                - RewritePath=/admin/users, /api/admin/users

            - id: admin-service
              uri: lb://auth-service
              predicates:
                - Path=/admin/users/**
              filters:
                - RewritePath=/admin/users/(?<segment>.*), /api/admin/users/${segment}

            - id: job-posting-admin-root
              uri: lb://job-posting-service
              predicates:
                - Path=/admin/jobs
              filters:
                - RewritePath=/admin/jobs, /api/admin/jobs

            - id: job-posting-admin
              uri: lb://job-posting-service
              predicates:
                - Path=/admin/jobs/**
              filters:
                - RewritePath=/admin/jobs/(?<segment>.*), /api/admin/jobs/${segment}

            - id: admin-application-service-root
              uri: lb://application-submit-service
              predicates:
                - Path=/admin/applications
              filters:
                - RewritePath=/admin/applications, /api/admin/applications



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}] %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: mySuperqfqfqfqfqfqSecretKey1afaff23456dfffafqfqffqfqf
  expiration: 3600000 # 1 hour in ms