server:
  port: 8082

spring:
  application:
    name: application-submit-service
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
    template:
      default-topic: resume-parse-topic

  data:
    mongodb:
      uri: mongodb://localhost:27017/applicationdb




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

cloudinary:
  cloud-name: dutvipg4f
  api-key: 314876564298642
  api-secret: KAoHzfGUhCCjjdNKlNlb_cDDWcY

kafka:
  topics:
    resume-parse: resume-parse-topic

jwt:
  secret: mySuperqfqfqfqfqfqSecretKey1afaff23456dfffafqfqffqfqf


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}] %m%n"