spring:
  application:
    name: eureka-server
  threads:
    virtual:
      enabled: true
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}] %m%n"