server:
  port: 9090


 # if using Bearer token
spring:
  application:
    name: spring-boot-admin-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}] %m%n"